### ISSUE TITLE
Passport Tutorial: Defining query variable in clickHandler.server.js

### ISSUE THREAD

**Issue by jondcoleman** [johnstonbl01/clementinejs#13]
`var query = { 'github.id': req.user.github.id };`  This is in the tutorial for clickHandler.

This doesn't work because req is undefined at this point (I think).

I looked at the source code and looks like you just put the query in each of the functions i.e. 

`.findOne({ 'github.id': req.user.github.id }, { '_id': false })`

**Comment by johnstonbl01** [comment]
Yep - believe you're right about it being undefined at that point, and is likely why I changed it.

**Comment by johnstonbl01** [comment]
Fixed - thanks for pointing this out!
