### ISSUE TITLE
Consider mentioning scenario where .gitignore is not present

### ISSUE THREAD

**Issue by regenerous** [johnstonbl01/clementinejs#14]
When I reached the **.gitignore** section in your tutorial (http://www.clementinejs.com/tutorials/tutorial-beginner.html) I looked in my directory and could not find a .gitignore file in my root directory (even with hidden files shown). While it may seem obvious to experienced coders, you may want to mention the fact that if the user does not have such a file, that they can create one but sending `touch .gitignore` and then opening the file using `nano .gitignore` to add the `node_modules/`. 

By adding this text, you let the user know that just because they don't have this .gitignore file does not mean they did something wrong in the previous steps (which is what I assume a lot of times when I am going through a tutorial and what I see does not match what the tutorial mentions).

**Comment by johnstonbl01** [comment]
Really nice suggestion.

**Comment by regenerous** [comment]
I can work on editing this tonight and submitting PR.
