### ISSUE TITLE
The following line is ambiguous: "At the top of the file: "

### ISSUE THREAD

**Issue by regenerous** [johnstonbl01/clementinejs#19]
**Location of issue**
Second sentence between the first two code blocks in the following section:
http://www.clementinejs.com/tutorials/tutorial-beginner.html#RefactoringRoutes

**Issue**
The following line is ambiguous: "At the top of the file: "

**Suggested Solution**
State which file you are referring to (server.js) since it may not be obvious to the user which of the two .js files you are referring to.

~~I can submit PR for this later tonight.~~

**Comment by johnstonbl01** [comment]
Would prefer if this were reworded to be like so:

The next order of business is to add our new route file as a dependency for the `server.js` file.

_server.js_:

``` js
'use strict';

var express = require('express'),
    routes = require('./app/routes/index.js');

var app = express();

...
```

**Comment by regenerous** [comment]
I will let you make the change then so you can edit it to your liking.

Is there a way for you to be able to highlight the lines that change in a file? The way the Ruby on Rails tutorial does it (https://www.railstutorial.org/book) is EXCELLENT and extremely clear.
