### ISSUE TITLE
Possible typo in Refactoring Routes section

### ISSUE THREAD

**Issue by regenerous** [johnstonbl01/clementinejs#20]
**Location of issue**
"Now we need to pass the Express application as an argument to our route function object." sentence in:
http://www.clementinejs.com/tutorials/tutorial-beginner.html#RefactoringRoutes

EDIT: also sentence: "This will allow us to use Express functionality within the scope of our new route function."

**Issue**
I think "route" should be "routes"

**Suggested Solution**
Fix typo. Unless of course you really did mean "route" and not "routes"

**Comment by johnstonbl01** [comment]
It's plural in the actual file. Should probably refer to it by the same reference (`routes` not routes or route).
