### ISSUE TITLE
Typo #2 in Refactoring Routes section

### ISSUE THREAD

**Issue by regenerous** [johnstonbl01/clementinejs#22]
Add comma between "Hello" and "world!" (placed in bold below) in second to last sentence of this section (http://www.clementinejs.com/tutorials/tutorial-beginner.html#RefactoringRoutes)

"Point the browser to localhost:3000 and you should again see "Hello**,** world!""

EDIT: another solution would be to fix the index.html section of this tutorial so that the user types in:

``` html
<body>
        <p>Hello world!</p>
</body>
```

(without comma) instead of 

``` html
<body>
        <p>Hello, world!</p>
</body>
```

**Comment by johnstonbl01** [comment]
Prefer to add comma rather than exclude it.
