### ISSUE TITLE
No instruction explicitly telling the user to save a copy of the Clementine logo to folder

### ISSUE THREAD

**Issue by regenerous** [johnstonbl01/clementinejs#28]
In **Adding Additional Elements to Index.html** section (http://www.clementinejs.com/tutorials/tutorial-beginner.html#AddingAdditionalElementstoIndex.html) there are no explicit instructions telling user to save Clementine logo to folder. Consider adding these instructions for users that are just following along and expecting same results you show later (with the logo present on the page).

**Comment by regenerous** [comment]
I suggest mentioning `curl -O [url]` command for retrieving the logo image for those using environments like C9.

**Comment by johnstonbl01** [comment]
Actually... The paragraph at the beginning, "I've added some Clementine features and text to the application, but feel free to modify however you like. If you'd like to include a copy of the Clementine logo, feel free to download a copy (right-click > Save Image As) from the this GitHub page. Make sure to save it within the /public/img directory."

I think that's sufficient in this case.

**Comment by regenerous** [comment]
That text does suggest how to do it but does not TELL the user to do it. In my opinion, when following tutorials, users need to be TOLD what to do. It's okay to suggest that they can use their own stuff or take their own path but for those users that are trying to follow the tutorial step by step to make sure they do everything right, it is more clear when you are told what to do. Also, it would still be nice to include the `curl` command in there for C9 users.

Let's put it this way... I read that text and read it as "You can do this if you like but it is not required in order to follow the rest of the tutorial" so I didn't do it. Then when it came time to display the image, I had to go back and get the image to put in the folder. Otherwise, I would have no way of checking if what I did in the tutorial was correct (or if i had a typo or something).

**Comment by johnstonbl01** [comment]
It's not required. You can put any image you want there in its place, which is why it's a suggestion. And now I think we know how `curl` worked out on c9. :smile:
