### ISSUE TITLE
Show where in the server.js file to place code snippet

### ISSUE THREAD

**Issue by regenerous** [johnstonbl01/clementinejs#29]
In **Adding Additional Elements to Index.html** section (http://www.clementinejs.com/tutorials/tutorial-beginner.html#AddingAdditionalElementstoIndex.html):

You do not specify where in the server.js file to place the following line of code:
`app.use('/public', express.static(process.cwd() + '/public'));`

This is very important. I would suggest adopting the way the https://www.railstutorial.org/book does it by showing parts of the file with `...` for the parts that already exist. Example:

---

This can be solved by adding `app.use('/public', express.static(process.cwd() + '/public'));` to the server.js file as shown below:

_server.js_

``` js
'use strict';
.
.
.
routes(app);

app.use('/public', express.static(process.cwd() + '/public'));

app.listen(8080, function() {...
.
.
.
```

**Comment by johnstonbl01** [comment]
Yep - agree that this should be done.

**Comment by ghost** [comment]
Hi - I would like to have a go at this please as a beginner. Should be done today. Thanks.

**Comment by ghost** [comment]
Should the pull request go on the gh-pages branch as it is documentation or development branch as requested in the Contributing Notes?

**Comment by ghost** [comment]
Pls ignore previous comment. Have reviewed previous merged documentation PRs and have put it on the gh-pages branch.

**Comment by johnstonbl01** [comment]
@Web-Dev-Rich Hi Rich. Thanks for the contribution! I've added a note to your pull request for a slight change.

**Comment by ghost** [comment]
Have made change as requested and committed. Not sure if I need to to do anything else to the pull request?
