### ISSUE TITLE
Clementine logo not loading when using curl to upload image to C9

### ISSUE THREAD

**Issue by regenerous** [johnstonbl01/clementinejs#30]
When you use the `curl` command to upload the Clementine logo to C9, the image does not show up. and you get the following error when you try to open it in C9:
![](https://files.gitter.im/johnstonbl01/clementinejs/SzEA/Screenshot_101415_101845_AM.jpg)

I suggest making a note of this in the tutorial just in case other users try to do the same thing.

**Comment by johnstonbl01** [comment]
Similar to #28.
