### ISSUE TITLE
Typos/Grammar in Connecting to MongoDB section

### ISSUE THREAD

**Issue by regenerous** [johnstonbl01/clementinejs#31]
(http://www.clementinejs.com/tutorials/tutorial-beginner.html#ConnectingtoMongoDB)

Second sentence missing "to". Added it here in bold: "The API will simply be a way for us **to** make our database data available to the front-end of the application.

Added letters in bold: "This function takes an err**or** as the first argument, and the database object as the second argument."

**Comment by kumarSC** [comment]
Hey guys, I landed here following yourfirstpr tweet, https://twitter.com/yourfirstpr/status/656077461273219073

I am going through the doc and trying to correct the typos.Will create a PR soon.This is my first PR so please let me know of any caution I should exercise.

**Comment by regenerous** [comment]
@kumarSC whoa! where did that tweet come from!? And why is my face splattered all over it? Is that a bot that crawls github for issues tagged as "beginner"?

Either way, welcome and good luck on your first PR. My first PR was on FCC but my first Merged PR was right here in the Clementine repo.

**Comment by johnstonbl01** [comment]
@kumarSC Unfortunately, someone had made a PR for that issue just prior to yours. However, there are a few other issues out there that would be great for a first PR! If you need any help, please feel free to let me know.
