### ISSUE TITLE
Code typos/omissions - Setting Up the Server-Side Controller section

### ISSUE THREAD

**Issue by regenerous** [johnstonbl01/clementinejs#32]
First code block in **Setting Up the Server-Side Controller** section (http://www.clementinejs.com/tutorials/tutorial-beginner.html#SettingUptheServer-SideController) has the following line of code that is not indented according to the code guidelines:
`thow err;`

It is also missing a semicolon after the closing parenthesis of `clicks.findOne({}, clickProjection... )` and an unnecessary semicolon after the closing curly bracket of `function clickHandler (db) { ... }`

The last bullet in the unordered list that explains each line of code (`res.json(results); - Send a response to the browser with a JSON version of the results array.`) is using `results`(plural) in two places instead of what's actually in the code which is `result` (singular). Change that bullet to read as follows: res.json(**result**); - Send a response to the browser with a JSON version of the **result** array.

**Comment by johnstonbl01** [comment]
The code snippet should be:

``` js
'use strict';

function clickHandler (db) {

    var clicks = db.collection('clicks');

    this.getClicks = function (req, res) {

        var clickProjection = { '_id': false };

        clicks.findOne({}, clickProjection, function (err, result) {
            if (err) {
               throw err;
            }

            res.json(result);
        });
    };
}

module.exports = clickHandler;
```

**Comment by gnbaron** [comment]
I can work on that? If yes, where is the tutorial page?

**Comment by johnstonbl01** [comment]
@guilhermefloriani That sounds fine. Tutorials are in the `gh-pages` branch. This particular tutorial is the `tutorials/tutorial-beginner.md` file. @hugoender linked to it above in the issue description.
