### ISSUE TITLE
Typo in the Simple Node Server section

### ISSUE THREAD

**Issue by regenerous** [johnstonbl01/clementinejs#34]
(http://www.clementinejs.com/tutorials/tutorial-beginner.html#SimpleNodeServer)

The new text you added to solve issue #18 has a typo: 

"For now, we'll need to stop and restart the Node server each time we make a change. To stop the server when it's running, use Ctrl+C in the terminal window. We can restart the Node server by simply typing $ node ~~server~~ **server.js** in the terminal window again."

**Comment by johnstonbl01** [comment]
Not a typo.
