### ISSUE TITLE
Logo in Beginner Tutorial page points to 404 page.

### ISSUE THREAD

**Issue by regenerous** [johnstonbl01/clementinejs#35]
The Clementine logo at the top of the following page...:
http://www.clementinejs.com/tutorials/tutorial-beginner.html

...points to:
http://www.clementinejs.com/home.html

Which is 404.

**Comment by regenerous** [comment]
Actually, turns out this is happening in a lot of your pages (if not all).

**Comment by johnstonbl01** [comment]
Yeah - it's all of them because they're templated.
