### ISSUE TITLE
Clementine logo image link

### ISSUE THREAD

**Issue by regenerous** [johnstonbl01/clementinejs#42]
In the beginner tutorial section (http://www.clementinejs.com/tutorials/tutorial-beginner.html#AddingAdditionalElementstoIndex.html):

There is a link to the Clementine logo so the user can download it and place it in their img folder. This link leads here: `https://github.com/johnstonbl01/clementinejs-angular/blob/master/public/img/clementine_150.png`. If you try to `curl` this url, it gives you a bogus image. 

Suggestion: have the link in the document point here: `https://raw.githubusercontent.com/johnstonbl01/clementinejs-angular/master/public/img/clementine_150.png` which is the **actual** location of the image file so that the user can then `curl` it.

**Comment by matyikriszta** [comment]
@hugoender just opened a PR for this, let me know if it needs work!
