### ISSUE TITLE
Error with sendFile on c9.io

### ISSUE THREAD

**Issue by chrisdziewa** [johnstonbl01/clementinejs#61]
I was given an error that sendFile was not a function when trying to serve the first file. Strangely, even though I am using the newest Express version, the deprecated `sendfile` works. Also I was able to use express's static function which worked fine as well: `app.use('/', express.static(__dirname));`. I'm not sure if this is a local issue or not.

**Comment by johnstonbl01** [comment]
Can you provide either 1) a link to the c9 workspace or 2) the contents of the route and server files?

**Comment by johnstonbl01** [comment]
Just tested with `sendFile` and newest version of Express. Didn't run into any issues.

**Comment by chrisdziewa** [comment]
It must just not like it on c9. I didn't have the routes separated. Very strange.

**Comment by johnstonbl01** [comment]
Identified as issue w/Express version < 4.0.
