### ISSUE TITLE
Typo sendFile should be sendfile

### ISSUE THREAD

**Issue by pattee** [johnstonbl01/clementinejs#64]
In the Refactoring Routes section the command res.sendFile(process.cwd() + '/index.html'); should not have the F in caps. Instead should be res.sendfile(process.cwd() + '/index.html');

**Comment by johnstonbl01** [comment]
@pattee Hi there!
What version of Express are you using? Prior to version 4.x, the method was `sendfile()`, as you can see here in the 3.x documentation: http://expressjs.com/en/3x/api.html#res.sendfile.

However, I recommend (and the tutorial is based off of) Express 4.x+, which uses `sendFile()`: http://expressjs.com/en/4x/api.html#res.sendFile.

**Comment by pattee** [comment]
Hi Blake,

Thank you for the clarification.  After submitting the ticket I noticed
that there were times when both were used online. This helps clarify the
reason.

Pattee

**Comment by johnstonbl01** [comment]
No problem. :) Best of luck!
