### ISSUE TITLE
bash: mongod: command not found

### ISSUE THREAD

**Issue by walijoy** [johnstonbl01/clementinejs#69]
https://clone-baoniu.c9users.io/
at c9.com  
clone from  https://github.com/johnstonbl01/clementinejs

$:mongod --smallfiles
res
bash: mongod: command not found

**Comment by johnstonbl01** [comment]
Try 'sudo apt-get install mongodb-org' in the terminal. Just found out a few days ago that c9 removed the mongo installation from the default workspace.

**Comment by walijoy** [comment]
yep, thank you

**Comment by FaisalGulzarDev** [comment]
It works, thanks
