### ISSUE TITLE
Database Fails To Connect?

### ISSUE THREAD

**Issue by borja-rojano** [johnstonbl01/clementinejs#73]
Dear John, 

I already expressed my thanks and admiration on Twitter but I reiterate: this boilerplate and tutorial you have created is one of the best resources I have encountered in my short journey to become a developer. 

I am following the basic tutorial and I have hit a roadblock. I got to the step where I connect the front end to the database but, even after triple checking that I have exactly the same code in my files (and after that, directly pasting your code for server.js) I get the following error as the `err` in the `mongo.connect` callback function:
`[MongoError: failed to connect to server [localhost:27017] on first connect]`

I have double checked that I have MongoDB installed. 

For reference, here is the current state of my boilerplate is found [here](https://github.com/borja-rojano/clementine).

I will keep trying to solve it on my own but I thought it would be nice for you and maybe others to know. 

Happy 2017!

**Comment by edwinharly** [comment]
"mongod" service needs to be running for you to connect to MongoDB. Run this command "sudo service mongod start" if you're using Ubuntu, for Windows you can check MongoDB official docs.

**Comment by johnstonbl01** [comment]
Hi there, @borja-rojano - Is this still something you're struggling with?

**Comment by borja-rojano** [comment]
Dear @johnstonbl01, 

thanks for asking. I have solved the issue because I am doing the course from mongo university that you recomended. If it wasn't for that course I feel I would be lost at this specific point of the clementine turorial. 

This is the only major hurdle for the basic tutorial really. The rest is super clear and easy to follow. Do you think it would be a good idea to have a specific section with a more detailed configuration of mongo db for people who have not followed the course? I would be happy to work on it and contribute to this awesome thing you have created.
Also, perhaps a pargraph or two in the main tutorial page explicitly indicating that the mongo needs to be activated could hep. To me, as a newbie, it was far from implicit.

**Comment by johnstonbl01** [comment]
@borja-rojano If you'd like to propose a few updates to the documentation, then feel free to open a pull request. :)

Keep in mind, though, that the tutorial will be drastically changed later this year when the new version of Clementine is released.
