### ISSUE TITLE
Github application signup instructions are out of date

### ISSUE THREAD

**Issue by MiloATH** [johnstonbl01/clementinejs#77]
Github has updated the user settings UI. Registering a GitHub application is fairly similar just the names of a few things has changed. [The passport setup instructions should be updated.](https://github.com/johnstonbl01/clementinejs/blob/gh-pages/tutorials/tutorial-passport.md#passport-server-side-integration) Also, a new screenshot might be a good idea.

**Comment by CharanyaR** [comment]
Have fixed this issue in the PR https://github.com/johnstonbl01/clementinejs/pull/83

Let me know if it is fine.
