### ISSUE TITLE
Documentation: Main page links are broken

### ISSUE THREAD

**Issue by amoedoamorim** [johnstonbl01/clementinejs#8]
The links to the following pages are broken:

About
Tutorials
Docs
Contribute

Apparently the {{ site.baseurl }} isn't being replaced by the correct value so the links are all like:

http://johnstonbl01.github.io/clementinejs/{{ site.baseurl }}/about.html

**Comment by johnstonbl01** [comment]
Hiya! Can you provide a screenshot? Everything appears to work fine when I view the site from multiple browsers. Or are you trying to view the site locally?

**Comment by amoedoamorim** [comment]
I am trying to view the site from github.io

Sure, here you are:

![404](https://cloud.githubusercontent.com/assets/766082/10247556/53e7ff70-68f0-11e5-8b66-420f9b18c34d.png)
![brokenlink](https://cloud.githubusercontent.com/assets/766082/10247557/53ed32ce-68f0-11e5-90e5-3797d5a761d1.png)

**Comment by johnstonbl01** [comment]
Ah gotcha. Thanks for pointing that out! Will get that fixed today.
