### ISSUE TITLE
Deprecated feature in Mongoose

### ISSUE THREAD

**Issue by cd-Zero** [johnstonbl01/clementinejs#80]
Server.js section in Clementine.js Passport Authentication Tutorial 

 the directions if followed gives me a deprecation warning if using following code. `mongoose.connect('mongodb://localhost:27017/clementinejs');`

changing code to following solves this issue.
`mongoose.connect('mongodb://localhost:27017/clementinejs', {useMongooseClient: true});`

**Comment by caulifla** [comment]
Not sure whether this is correct. But [this](http://mongoosejs.com/docs/connections.html#use-mongo-client) states `Please opt in to the new connection logic using the useMongoClient option`. And `Mongoose's default connection logic is deprecated as of 4.11.0.` Hope this helps.

**Comment by SillasMC** [comment]
Is this issue still required? I can take a look at it
